### ISSUE TITLE
PHP an neues Datumsformat anpassen

### ISSUE THREAD

**Issue by EckigerLuca** [ifheroes/infinityheroes-bot#10]
Das Datumsformat der Export Dateien hat sich geändert. Neues Format ist in der `README.MD` aber drin.

PHP muss dem entsprechend angepasst werden (ich kann kein Französisch)

**Comment by chrischivlog** [comment]
@EckigerLuca Danke für deinen Issue: 

Ich habe gesehen das Du aktuell auch eine Änderung an der Konfig-File gemacht hast. Hier kam der Wert für MongoDB hinzu. Hier wollte ich das Docker Image anpassen damit es in unsere Docker Farm integriert werden kann. Allerdings erhalte ich beim Starten folgenden Fehler: 

```
2024-11-17 12:41:25 AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
2024-11-17 12:41:27 /bot/node_modules/mongodb-connection-string-url/lib/index.js:86
2024-11-17 12:41:27             throw new MongoParseError('Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"');
2024-11-17 12:41:27             ^
2024-11-17 12:41:27 
2024-11-17 12:41:27 MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
2024-11-17 12:41:27     at new ConnectionString (/bot/node_modules/mongodb-connection-string-url/lib/index.js:86:19)
2024-11-17 12:41:27     at parseOptions (/bot/node_modules/mongodb/lib/connection_string.js:186:17)
2024-11-17 12:41:27     at new MongoClient (/bot/node_modules/mongodb/lib/mongo_client.js:51:63)
2024-11-17 12:41:27     at Object.<anonymous> (/bot/src/index.js:13:18)
2024-11-17 12:41:27     at Module._compile (node:internal/modules/cjs/loader:1267:14)
2024-11-17 12:41:27     at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
2024-11-17 12:41:27     at Module.load (node:internal/modules/cjs/loader:1125:32)
2024-11-17 12:41:27     at Module._load (node:internal/modules/cjs/loader:965:12)
2024-11-17 12:41:27     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
2024-11-17 12:41:27     at node:internal/main/run_main_module:23:47
2024-11-17 12:41:27 
2024-11-17 12:41:27 Node.js v20.0.0
2024-11-17 12:41:26 Starting Apache httpd web server: apache2.
2024-11-17 12:41:26 
2024-11-17 12:41:26 > infinityheroes-bot@1.2.1 start
2024-11-17 12:41:26 > node ./src/index.js
2024-11-17 12:41:26 
```

Konnte leider auf meiner Seite in Docker nichts finden, die Variablen werden wie in der sample config beschrieben übergeben. 

Ich übergebe im Moment keine MongoDB-Adresse in der compose.yml. Hier ein Auszug: 

```yaml
services:
  ifheroesbot:
    restart: always
    build:
      args:
      - token=
      - clientId=829318719138299934
      - guildId=
      - roleId=990280061145985075
      - color=fff
      - api_url=https://api.ifheroes.de/v1/news
      - botAdminRole=990280061145985075
      - mongodbURI=
    ports:
    - "8080:8080"

    volumes:
      - ./exports:/bot/exports



```

**Comment by EckigerLuca** [comment]
Nuja, der Bot startet letztlich nur, wenn eine DB vorhanden ist. Kannst du vielleicht mal versuchen einen Dummy-String einzufügen?
`mongodb://` könnte vielleicht reichen.

**Comment by chrischivlog** [comment]
Ok, ich hab es nochmal mit einem Dummy versucht. Mit einer vollständigen Mongo-Adresse hat es funktioniert. Natürlich startet er jetzt jedes mal nach einem Timeout durch wenn er den Server nicht findet.


**Ich schau mal die anpassung sollte ich ohne große Probleme hin bekommen. Ich würde dann aber erstmal warten wollen bis die MongoDB vorhanden ist.**

Adresse:
```     
- mongodbURI=mongodb://<>:<>@cluster-shard-00-00.mongodb.net:27017,cluster-shard-00-01.mongodb.net:27017,cluster-shard-00-02.mongodb.net:27017/mydatabase?replicaSet=atlas-xyz-shard-0&ssl=true&authSource=admin
```

Fehler in der Konsole:

```
ifheroesbot-1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.2. Set the 'ServerName' directive globally to suppress this message
ifheroesbot-1  | .
ifheroesbot-1  | 
ifheroesbot-1  | > infinityheroes-bot@1.2.1 start
ifheroesbot-1  | > node ./src/index.js
ifheroesbot-1  | 
ifheroesbot-1  | ┃ 2024-11-17 20:58:44:45 [SUCCESS]: Ready! Logged in as Py-test-bot#4611
ifheroesbot-1  | /bot/node_modules/mongodb/lib/sdam/topology.js:276
ifheroesbot-1  |             const timeoutError = new error_1.MongoServerSelectionError(`Server selection timed out after ${options.serverSelectionTimeoutMS} ms`, this.description);
ifheroesbot-1  |                                  ^
ifheroesbot-1  | 
ifheroesbot-1  | MongoServerSelectionError: getaddrinfo ENOTFOUND cluster-shard-00-00.mongodb.net
ifheroesbot-1  |     at EventTarget.<anonymous> (/bot/node_modules/mongodb/lib/sdam/topology.js:276:34)
ifheroesbot-1  |     at [nodejs.internal.kHybridDispatch] (node:internal/event_target:761:20)
ifheroesbot-1  |     at EventTarget.dispatchEvent (node:internal/event_target:703:26)
ifheroesbot-1  |     at abortSignal (node:internal/abort_controller:314:10)
ifheroesbot-1  |     at TimeoutController.abort (node:internal/abort_controller:332:5)
ifheroesbot-1  |     at Timeout.<anonymous> (/bot/node_modules/mongodb/lib/utils.js:1011:92)
ifheroesbot-1  |     at listOnTimeout (node:internal/timers:573:17)
ifheroesbot-1  |     at process.processTimers (node:internal/timers:514:7) {
ifheroesbot-1  |   reason: TopologyDescription {
ifheroesbot-1  |     type: 'ReplicaSetNoPrimary',
ifheroesbot-1  |     servers: Map(3) {
ifheroesbot-1  |       'cluster-shard-00-00.mongodb.net:27017' => ServerDescription {
ifheroesbot-1  |         address: 'cluster-shard-00-00.mongodb.net:27017',
ifheroesbot-1  |         type: 'Unknown',
ifheroesbot-1  |         hosts: [],
ifheroesbot-1  |         passives: [],
ifheroesbot-1  |         arbiters: [],
ifheroesbot-1  |         tags: {},
ifheroesbot-1  |         minWireVersion: 0,
ifheroesbot-1  |         maxWireVersion: 0,
ifheroesbot-1  |         roundTripTime: -1,
ifheroesbot-1  |         lastUpdateTime: 1618189,
ifheroesbot-1  |         lastWriteDate: 0,
ifheroesbot-1  |         error: MongoNetworkError: getaddrinfo ENOTFOUND cluster-shard-00-00.mongodb.net
ifheroesbot-1  |             at connectionFailureError (/bot/node_modules/mongodb/lib/cmap/connect.js:379:20)
ifheroesbot-1  |             at TLSSocket.<anonymous> (/bot/node_modules/mongodb/lib/cmap/connect.js:285:22)
ifheroesbot-1  |             at Object.onceWrapper (node:events:626:26)
ifheroesbot-1  |             at TLSSocket.emit (node:events:511:28)
ifheroesbot-1  |             at emitErrorNT (node:internal/streams/destroy:151:8)
ifheroesbot-1  |             at emitErrorCloseNT (node:internal/streams/destroy:116:3)
ifheroesbot-1  |             at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
ifheroesbot-1  |           [Symbol(errorLabels)]: Set(1) { 'ResetPool' },
ifheroesbot-1  |           [cause]: Error: getaddrinfo ENOTFOUND cluster-shard-00-00.mongodb.net
ifheroesbot-1  |               at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
ifheroesbot-1  |             errno: -3008,
ifheroesbot-1  |             code: 'ENOTFOUND',
ifheroesbot-1  |             syscall: 'getaddrinfo',
ifheroesbot-1  |             hostname: 'cluster-shard-00-00.mongodb.net'
ifheroesbot-1  |           }
ifheroesbot-1  |         },
ifheroesbot-1  |         topologyVersion: null,
ifheroesbot-1  |         setName: null,
ifheroesbot-1  |         setVersion: null,
ifheroesbot-1  |         electionId: null,
ifheroesbot-1  |         logicalSessionTimeoutMinutes: null,
ifheroesbot-1  |         primary: null,
ifheroesbot-1  |         me: null,
ifheroesbot-1  |         '$clusterTime': null
ifheroesbot-1  |       },
ifheroesbot-1  |       'cluster-shard-00-01.mongodb.net:27017' => ServerDescription {
ifheroesbot-1  |         address: 'cluster-shard-00-01.mongodb.net:27017',
ifheroesbot-1  |         type: 'Unknown',
ifheroesbot-1  |         hosts: [],
ifheroesbot-1  |         passives: [],
ifheroesbot-1  |         arbiters: [],
ifheroesbot-1  |         tags: {},
ifheroesbot-1  |         minWireVersion: 0,
ifheroesbot-1  |         maxWireVersion: 0,
ifheroesbot-1  |         roundTripTime: -1,
ifheroesbot-1  |         lastUpdateTime: 1618194,
ifheroesbot-1  |         lastWriteDate: 0,
ifheroesbot-1  |         error: MongoNetworkError: getaddrinfo ENOTFOUND cluster-shard-00-01.mongodb.net
ifheroesbot-1  |             at connectionFailureError (/bot/node_modules/mongodb/lib/cmap/connect.js:379:20)
ifheroesbot-1  |             at TLSSocket.<anonymous> (/bot/node_modules/mongodb/lib/cmap/connect.js:285:22)
ifheroesbot-1  |             at Object.onceWrapper (node:events:626:26)
ifheroesbot-1  |             at TLSSocket.emit (node:events:511:28)
ifheroesbot-1  |             at emitErrorNT (node:internal/streams/destroy:151:8)
ifheroesbot-1  |             at emitErrorCloseNT (node:internal/streams/destroy:116:3)
ifheroesbot-1  |             at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
ifheroesbot-1  |           [Symbol(errorLabels)]: Set(1) { 'ResetPool' },
ifheroesbot-1  |           [cause]: Error: getaddrinfo ENOTFOUND cluster-shard-00-01.mongodb.net
ifheroesbot-1  |               at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
ifheroesbot-1  |             errno: -3008,
ifheroesbot-1  |             code: 'ENOTFOUND',
ifheroesbot-1  |             syscall: 'getaddrinfo',
ifheroesbot-1  |             hostname: 'cluster-shard-00-01.mongodb.net'
ifheroesbot-1  |           }
ifheroesbot-1  |         },
ifheroesbot-1  |         topologyVersion: null,
ifheroesbot-1  |         setName: null,
ifheroesbot-1  |         setVersion: null,
ifheroesbot-1  |         electionId: null,
ifheroesbot-1  |         logicalSessionTimeoutMinutes: null,
ifheroesbot-1  |         primary: null,
ifheroesbot-1  |         me: null,
ifheroesbot-1  |         '$clusterTime': null
ifheroesbot-1  |       },
ifheroesbot-1  |       'cluster-shard-00-02.mongodb.net:27017' => ServerDescription {
ifheroesbot-1  |         address: 'cluster-shard-00-02.mongodb.net:27017',
ifheroesbot-1  |         type: 'Unknown',
ifheroesbot-1  |         hosts: [],
ifheroesbot-1  |         passives: [],
ifheroesbot-1  |         arbiters: [],
ifheroesbot-1  |         tags: {},
ifheroesbot-1  |         minWireVersion: 0,
ifheroesbot-1  |         maxWireVersion: 0,
ifheroesbot-1  |         roundTripTime: -1,
ifheroesbot-1  |         lastUpdateTime: 1618218,
ifheroesbot-1  |         lastWriteDate: 0,
ifheroesbot-1  |         error: MongoNetworkError: getaddrinfo ENOTFOUND cluster-shard-00-02.mongodb.net
ifheroesbot-1  |             at connectionFailureError (/bot/node_modules/mongodb/lib/cmap/connect.js:379:20)
ifheroesbot-1  |             at TLSSocket.<anonymous> (/bot/node_modules/mongodb/lib/cmap/connect.js:285:22)
ifheroesbot-1  |             at Object.onceWrapper (node:events:626:26)
ifheroesbot-1  |             at TLSSocket.emit (node:events:511:28)
ifheroesbot-1  |             at emitErrorNT (node:internal/streams/destroy:151:8)
ifheroesbot-1  |             at emitErrorCloseNT (node:internal/streams/destroy:116:3)
ifheroesbot-1  |             at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
ifheroesbot-1  |           [Symbol(errorLabels)]: Set(1) { 'ResetPool' },
ifheroesbot-1  |           [cause]: Error: getaddrinfo ENOTFOUND cluster-shard-00-02.mongodb.net
ifheroesbot-1  |               at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
ifheroesbot-1  |             errno: -3008,
ifheroesbot-1  |             code: 'ENOTFOUND',
ifheroesbot-1  |             syscall: 'getaddrinfo',
ifheroesbot-1  |             hostname: 'cluster-shard-00-02.mongodb.net'
ifheroesbot-1  |           }
ifheroesbot-1  |         },
ifheroesbot-1  |         topologyVersion: null,
ifheroesbot-1  |         setName: null,
ifheroesbot-1  |         setVersion: null,
ifheroesbot-1  |         electionId: null,
ifheroesbot-1  |         logicalSessionTimeoutMinutes: null,
ifheroesbot-1  |         primary: null,
ifheroesbot-1  |         me: null,
ifheroesbot-1  |         '$clusterTime': null
ifheroesbot-1  |       }
ifheroesbot-1  |     },
ifheroesbot-1  |     stale: false,
ifheroesbot-1  |     compatible: true,
ifheroesbot-1  |     heartbeatFrequencyMS: 10000,
ifheroesbot-1  |     localThresholdMS: 15,
ifheroesbot-1  |     setName: 'atlas-xyz-shard-0',
ifheroesbot-1  |     maxElectionId: null,
ifheroesbot-1  |     maxSetVersion: null,
ifheroesbot-1  |     commonWireVersion: 0,
ifheroesbot-1  |     logicalSessionTimeoutMinutes: null
ifheroesbot-1  |   },
ifheroesbot-1  |   code: undefined,
ifheroesbot-1  |   [Symbol(errorLabels)]: Set(0) {},
ifheroesbot-1  |   [cause]: MongoNetworkError: getaddrinfo ENOTFOUND cluster-shard-00-00.mongodb.net
ifheroesbot-1  |       at connectionFailureError (/bot/node_modules/mongodb/lib/cmap/connect.js:379:20)
ifheroesbot-1  |       at TLSSocket.<anonymous> (/bot/node_modules/mongodb/lib/cmap/connect.js:285:22)
ifheroesbot-1  |       at Object.onceWrapper (node:events:626:26)
ifheroesbot-1  |       at TLSSocket.emit (node:events:511:28)
ifheroesbot-1  |       at emitErrorNT (node:internal/streams/destroy:151:8)
ifheroesbot-1  |       at emitErrorCloseNT (node:internal/streams/destroy:116:3)
ifheroesbot-1  |       at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
ifheroesbot-1  |     [Symbol(errorLabels)]: Set(1) { 'ResetPool' },
ifheroesbot-1  |     [cause]: Error: getaddrinfo ENOTFOUND cluster-shard-00-00.mongodb.net
ifheroesbot-1  |         at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
ifheroesbot-1  |       errno: -3008,
ifheroesbot-1  |       code: 'ENOTFOUND',
ifheroesbot-1  |       syscall: 'getaddrinfo',
ifheroesbot-1  |       hostname: 'cluster-shard-00-00.mongodb.net'
ifheroesbot-1  |     }
ifheroesbot-1  |   }
ifheroesbot-1  | }

```
